apiVersion: 1

datasources:
  - name: Postgres
    uid: postgres
    type: postgres
    access: proxy
    url: db:5432
    database: astro_reason
    user: postgres
    secureJsonData:
      password: postgres
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timeInterval: "1m"
